# YOLO App Docker Compose - Updated for persistent uploads and networking

services:

  # Frontend (React)
  brian-yolo-client:
    image: brianbwire/brian-yolo-client:v1.0.0
    build: ./client
    container_name: brian-yolo-client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - brian-yolo-backend
    environment:
      - REACT_APP_API_URL=http://brian-yolo-backend:5000
    networks:
      - app-net

  # Backend (Node.js)
  brian-yolo-backend:
    image: brianbwire/brian-yolo-backend:v1.0.0
    build: ./backend
    container_name: brian-yolo-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://app-mongo:27017/yolo_db
      - NODE_ENV=production
      - PORT=5000
    depends_on:
      - app-mongo
    volumes:
      # Persist uploads folder between container rebuilds
      - ./backend/uploads:/usr/src/app/uploads
    networks:
      - app-net

  # MongoDB
  app-mongo:
    image: mongo:latest
    container_name: app-mongo
    ports:
      - "27017:27017"
    volumes:
      # Persist database data
      - app-mongo-data:/data/db
    networks:
      - app-net

# Network
networks:
  app-net:
    driver: bridge
    attachable: true

# Volumes
volumes:
  app-mongo-data:
    driver: local
